# Generated by Django 5.0.6 on 2025-02-18 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(choices=[('2025-2026', '2025-2026'), ('2024-2025', '2024-2025'), ('2023-2024', '2023-2024')], max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Law', 'Law'), ('Business Administration', 'Business Administration'), ('Laboratory', 'Laboratory'), ('Information Technology', 'Information Technology'), ('Project Management', 'Project Management'), ('Community Development', 'Community Development'), ('Electricity', 'Electricity')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Technician Certificate', 'Technician Certificate'), ('Ordinary Diploma', 'Ordinary Diploma'), ('Advanced Diploma', 'Advanced Diploma'), ('Postgraduate Diploma', 'Postgraduate Diploma'), ('Bachelor Degree', 'Bachelor Degree'), ('Masters Degree', 'Masters Degree')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Evening', 'Evening'), ('Morning', 'Morning'), ('Fulltime', 'Fulltime')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearOfStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Law', 'Law'), ('Business Administration', 'Business Administration'), ('Laboratory', 'Laboratory'), ('Information Technology', 'Information Technology'), ('Project Management', 'Project Management'), ('Community Development', 'Community Development'), ('Electricity', 'Electricity')], max_length=100)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.academicyear')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.level')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stream')),
                ('year_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.yearofstudy')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.academicyear')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.level')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.programme')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=20, unique=True)),
                ('fullname', models.CharField(max_length=200)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.academicyear')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.level')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.programme')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stream')),
                ('year_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.yearofstudy')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('question', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='quizzes/')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.academicyear')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.level')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.programme')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stream')),
                ('year_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.yearofstudy')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('question', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.academicyear')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.level')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.programme')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stream')),
                ('year_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.yearofstudy')),
            ],
        ),
    ]
